import Header from './components/header/header';
import './globals.css';
import localFont from 'next/font/local';

const estedadFont = localFont({
  src: [
    {
      path: '../public/fonts/Estedad-Regular.woff2',
      weight: '400',
    },
    {
      path: '../public/fonts/Estedad-Bold.woff2',
      weight: '800',
    },
    {
      path: '../public/fonts/Estedad-SemiBold.woff2',
      weight: '600',
    },
    {
      path: '../public/fonts/Estedad-Medium.woff2',
      weight: '500',
    },
  ],
  variable: '--font-estedad',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${estedadFont.className} container mx-auto max-w-[1440px] w-full`}
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
